### ISSUE TITLE
Lack of monetisation

### ISSUE THREAD

**Issue by skessler79** [ChooJunIan/odin-landing-page#1]
There appears to be a severe lack of monetisation in this project. Please consider adding more monetisation options.

**Comment by ChooJunIan** [comment]
Microtransactions will come along the way. In the meantime, senpai will need to teach me more about setting up HTTPS web server with C++. I think Intel wants me to do that in Kulim too.

**Comment by skessler79** [comment]
Guide to socket network programming: https://beej.us/guide/bgnet/

As for HTTPS, you'll need to find out how to enable SSL for the server

**Comment by ChooJunIan** [comment]
Damn alright, i got a lot more to learn

**Comment by skessler79** [comment]
have you considered turning your source code into an NFT?

**Comment by ChooJunIan** [comment]
No sir. My code is worthless. 2 worthless things don't make it worthy later.

**Comment by ChooJunIan** [comment]
Will monetise later, someday. One day. Copium.
